import test from 'node:test';
import assert from 'node:assert/strict';
import {createRentalDocumentDraft,deleteRentalDocumentDraft,leaseReviewFlags} from '../assets/js/rental-service.js';
function fixture(){return {properties:[{id:'p1'}],units:[{id:'u1',propertyId:'p1'}],tenancies:[{id:'t1',unitId:'u1'}],documents:[],usagePeriods:[],contractTerms:[],accountingPeriods:[],expenses:[],allocationRules:[],meters:[],readings:[],cashflows:[],checkItems:[],attachments:[]};}
test('Mietservice legt nur einen nicht freigegebenen Entwurf an',()=>{const r=createRentalDocumentDraft(fixture(),{documentId:'d1',type:'lease_draft',propertyId:'p1',unitId:'u1',tenancyId:'t1',createdOn:'2026-09-24',fields:{baseRentCents:100000,depositCents:300000}});assert.equal(r.project.documents[0].status,'draft');assert.equal(r.project.documents[0].legalRelease,false);assert.equal(r.project.documents[0].pdfGenerated,false);});
test('Kaution über drei Nettokaltmieten wird als Prüfhinweis markiert',()=>{assert.deepEqual(leaseReviewFlags({baseRentCents:100000,depositCents:300001}),['deposit_above_three_net_rents']);});
test('Fremdes Mietverhältnis wird abgewiesen',()=>{assert.throws(()=>createRentalDocumentDraft(fixture(),{documentId:'d1',type:'lease_draft',propertyId:'p1',unitId:'u1',tenancyId:'other',createdOn:'2026-09-24',fields:{}}),/Mietverhältnis/);});
test('Freigegebener Entwurf kann nicht gelöscht werden',()=>{const p=fixture();p.documents.push({id:'d1',type:'lease_draft',source:'baustein5-mietservice-v1',status:'released'});assert.throws(()=>deleteRentalDocumentDraft(p,{documentId:'d1'}),/Freigegebene/);});
test('Mietvertragsentwurf braucht ein konkretes Mietverhältnis',()=>{assert.throws(()=>createRentalDocumentDraft(fixture(),{documentId:'d2',type:'lease_draft',propertyId:'p1',unitId:'u1',createdOn:'2026-09-24',fields:{}}),/konkretes Mietverhältnis/);});
test('Ein- und Auszugsprotokoll braucht ein konkretes Mietverhältnis',()=>{assert.throws(()=>createRentalDocumentDraft(fixture(),{documentId:'d3',type:'handover_protocol',propertyId:'p1',unitId:'u1',createdOn:'2026-09-24',fields:{}}),/konkretes Mietverhältnis/);});
test('Mieter-Serviceblatt braucht ein konkretes Mietverhältnis',()=>{assert.throws(()=>createRentalDocumentDraft(fixture(),{documentId:'d4',type:'tenant_service_sheet',propertyId:'p1',unitId:'u1',createdOn:'2026-09-24',fields:{}}),/konkretes Mietverhältnis/);});
test('Hausordnung und Entsorgungsinformation bleiben ohne Mietverhältnis möglich',()=>{let p=fixture();p=createRentalDocumentDraft(p,{documentId:'d5',type:'house_rules',propertyId:'p1',unitId:'u1',createdOn:'2026-09-24',fields:{}}).project;p=createRentalDocumentDraft(p,{documentId:'d6',type:'waste_info',propertyId:'p1',unitId:'u1',createdOn:'2026-09-24',fields:{}}).project;assert.equal(p.documents.length,2);assert.equal('tenancyId' in p.documents[0],false);assert.equal('tenancyId' in p.documents[1],false);});
