(()=>{
'use strict';
/* FSA_PDF_CORE_V3
   Fester FSA-Basisbaustein fuer echte PDF-Dateierzeugung und benannten Download.
   Kein Browser-Druckdialog. Kein automatischer Share-Aufruf. Die fertige PDF wird
   nach der Erzeugung als sichtbarer Download mit festem Dateinamen angeboten. */
const CORE_VERSION='FSA_PDF_CORE_V3';
const EXPORTER_VERSION='FSA_PDF_DOCUMENT_EXPORT_V3';
let originalTitle=null,activeFilename='',restoreTimer=null,exporterPromise=null,pendingUrl='';
const safeName=s=>(String(s||'notfallakte').trim().replace(/[^a-zA-Z0-9äöüÄÖÜß_-]+/g,'-').replace(/^-+|-+$/g,'')||'notfallakte');
const stamp=(d=new Date())=>{const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}`};
const buildFilename=({demo=false,owner='',date=new Date()}={})=>`${demo?'DEMO-':''}Notfallakte-${safeName(owner)}-${stamp(date)}.pdf`;
function applyTitle(filename){activeFilename=filename;if(originalTitle===null)originalTitle=document.title;const base=filename.replace(/\.pdf$/i,'');document.title=base;document.documentElement.setAttribute('data-fsa-pdf-filename',filename);try{sessionStorage.setItem('fsa_notfallakte_pdf_filename',filename)}catch{}let meta=document.querySelector('meta[name="application-name"]');if(!meta){meta=document.createElement('meta');meta.name='application-name';document.head.appendChild(meta)}meta.content=base;return base}
function prepare(opts={}){clearTimeout(restoreTimer);const filename=buildFilename(opts);applyTitle(filename);return{filename,base:filename.replace(/\.pdf$/i,''),version:CORE_VERSION}}
function reassert(){if(activeFilename)applyTitle(activeFilename)}
function markPrintDialogClosed(){clearTimeout(restoreTimer);restoreTimer=setTimeout(restore,20000)}
function restore(){clearTimeout(restoreTimer);if(originalTitle!==null)document.title=originalTitle;originalTitle=null;activeFilename='';document.documentElement.removeAttribute('data-fsa-pdf-filename')}
function ensureActionBox(){let box=document.getElementById('v08ActionBox');if(box)return box;box=document.createElement('div');box.id='v08ActionBox';box.className='v08ActionBox';box.innerHTML='<div class="v08ActionTitle" id="v08ActionTitle"></div><div class="v08ActionText" id="v08ActionText"></div><div class="v08ActionFile" id="v08ActionFile" style="display:none"></div><div class="v08ActionButtons" id="v08ActionButtons"></div>';document.querySelector('.toolbar')?.insertAdjacentElement('afterend',box);return box}
function showBox(title,text='',file='',download=null){const box=ensureActionBox();if(!box)return;box.className='v08ActionBox show';const t=document.getElementById('v08ActionTitle'),x=document.getElementById('v08ActionText'),f=document.getElementById('v08ActionFile'),buttons=document.getElementById('v08ActionButtons');if(t)t.textContent=title;if(x)x.textContent=text;if(f){f.style.display=file?'block':'none';f.textContent=file||''}if(buttons){buttons.innerHTML='';if(download){const a=document.createElement('a');a.className='btn primary mini';a.textContent='PDF herunterladen / speichern';a.href=download.url;a.download=download.filename;a.setAttribute('type','application/pdf');a.addEventListener('click',()=>{setTimeout(()=>showBox('✓ PDF-Download gestartet','Speichere die fertige PDF jetzt an deinem gewünschten Speicherort. Zum Ausdrucken öffnest du später einfach diese gespeicherte PDF.',download.filename,download),80)});buttons.appendChild(a)}const ok=document.createElement('button');ok.className='btn secondary mini';ok.textContent='Bestätigen';ok.onclick=()=>box.classList.remove('show');buttons.appendChild(ok)}box.scrollIntoView?.({behavior:'smooth',block:'nearest'})}
function ensureExporter(){if(window.NotfallaktePdfExport?.version===EXPORTER_VERSION)return Promise.resolve(window.NotfallaktePdfExport);window.NotfallaktePdfExport=null;exporterPromise=null;exporterPromise=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-fsa-pdf-export]');if(old)old.remove();const s=document.createElement('script');s.src=`./pdf-document-export-v3.js?v=${EXPORTER_VERSION}`;s.async=true;s.dataset.fsaPdfExport='1';s.onload=()=>window.NotfallaktePdfExport?.version===EXPORTER_VERSION?resolve(window.NotfallaktePdfExport):reject(new Error('Aktuelle PDF-Engine wurde nicht geladen.'));s.onerror=()=>reject(new Error('PDF-Engine konnte nicht geladen werden.'));document.head.appendChild(s)});return exporterPromise}
function setPending(blob,filename){if(pendingUrl)URL.revokeObjectURL(pendingUrl);pendingUrl=URL.createObjectURL(blob);return{url:pendingUrl,filename}}
async function generatedPdf(){const filename=activeFilename||buildFilename({demo:typeof demoMode!=='undefined'&&!!demoMode,owner:typeof state!=='undefined'?state.owner:''});applyTitle(filename);try{const engine=await ensureExporter();showBox('PDF wird erzeugt','Die Notfallakte wird jetzt vollständig lokal erzeugt. Danach erscheint ein separater Button zum Herunterladen und Speichern.',filename);const result=await engine.generate({filename,onProgress:(done,total)=>{if(done===1||done===total||done%10===0)showBox(`PDF wird erzeugt – ${done} von ${total} Seiten`,'Die PDF wird lokal aufgebaut. Bitte warte, bis der separate Download-Button erscheint.',filename)}});const download=setPending(result.blob,filename);showBox('✓ PDF erfolgreich erstellt',`Die Notfallakte wurde mit ${result.pages} Seiten fertig erzeugt. Prüfe den Dateinamen und klicke erst jetzt auf „PDF herunterladen / speichern“.`,filename,download)}catch(err){console.error(err);showBox('PDF konnte nicht erstellt werden',err?.message||'Unbekannter Fehler bei der PDF-Erzeugung.',filename)}}
function relabel(){const b=document.getElementById('printBtn');if(b)b.textContent='Notfallakte als PDF erstellen'}
window.addEventListener('pagehide',()=>{if(pendingUrl)URL.revokeObjectURL(pendingUrl)});
window.NotfallaktePdfCore=Object.freeze({version:CORE_VERSION,buildFilename,prepare,reassert,markPrintDialogClosed,restore,printDelay:0,ensureExporter});
window.print=generatedPdf;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',relabel,{once:true});else relabel();
})();
